### PR TITLE
Added Waypoint Support (TomTom and Built-In) and updated accuracy for Continent Pins

### PR DESCRIPTION
**Pull request by fubaWoW**
Hi there!
I've added Support for TomTom and Built-In Waypoint System if TomTom is not available when "Right-Click" your Map Pins on a at the Continent Map.  
Also updated the Accuracy of most Dungeon Entrances for the Continent Map!

Maybe you don't like where i put the new functions because you got a better structure then i made :P

You can also add this feature on the Original Dungeon Entrance Pins.  
I've done this in my own little "myself" AddOn ;)  
The biggest problem at this point -> you need to "replace" a Blizzard function to get it work properly!  
A hook will not prevent from open the Encounter Journal and will close the Map instantly :(

Because of this i did not add it in the Pull Request, maybe you don't like it this way.  

Anyway, here is the Code for "Waypoints on Original Dungeon Entrance Pins":
```
-- Waypoint for Dungeon Entrance Pins
local function WaypointDungeonEntrancePinMixin(self, button)
	local useWaypoints = true
	local useTomTom = true
	local wp_mapid, wp_x, wp_y, wp_name
	useTomTom = useTomTom and (TomTom ~= nil) or false

	if (button == "LeftButton" and IsShiftKeyDown() and useWaypoints == true) then
		if IsControlKeyDown() then useTomTom = false end
		local uiMapID = self:GetMap():GetMapID();
		local journalInstanceID = self.journalInstanceID		
		
		local dungeonEntrances = C_EncounterJournal.GetDungeonEntrancesForMap(uiMapID);
		for i, dungeonEntranceInfo in ipairs(dungeonEntrances) do
			if dungeonEntranceInfo.journalInstanceID == journalInstanceID then
				wp_mapid = uiMapID
				wp_x = dungeonEntranceInfo.position.x
				wp_y = dungeonEntranceInfo.position.y
				wp_name = dungeonEntranceInfo.name or "Waypoint"
			end
		end
		
		-- if no "dungeonEntranceInfo" is found, use Pin itself as Source
		if (not wp_mapid) then
			wp_mapid = self:GetMap():GetMapID();
			wp_x, wp_y = self:GetPosition()
			wp_name = self.name or "Waypoint"
		end
	else -- if not
		EncounterJournal_LoadUI();
		EncounterJournal_OpenJournal(nil, self.journalInstanceID);
	end
	
	if (button == "LeftButton" and IsShiftKeyDown() and useWaypoints == true) and wp_mapid and wp_x and wp_y and wp_name then
		AddWaypoint(wp_mapid, wp_x, wp_y, wp_name, useTomTom)
	end
end
_G.DungeonEntrancePinMixin.OnMouseClickAction = WaypointDungeonEntrancePinMixin
```
this also requires the function `AddWaypoint` i've added in your "IPInstancePortalPinTemplate.lua"

Hopefully you like the changes and maybe we will see Waypoint support soon as Release Version ;)

and sorry for the "Wall of Text" :P

greetings,
fuba

### CODE REVIEW

**Comment by fubaWoW** [comment]
Update for 9.2 and fixed Waypoint Integration
Almost ALL Continent Pins are **WAY** more accurate now!

**Comment by steventroughtonsmith** [comment]
Hey @fubaWoW 

Some of these changes look great!, but your accuracy changes to the pin locations is counter to the reason many of those locations were inaccurate in the first place: I wanted the portal indicators to match up with the illustrations on the map, not their precise coords — which makes it much easier for people to understand where they should go. Here's the perennial example of Tempest Keep, which, if marked accurate to the coords, makes no sense on the map, and doesn't visually guide you to the right location (using your repo).

Screenshot 2022-11-22 214743

The only real reason I haven't merged your changes before now is because to make this work properly for the map the way I'd like, one would have to go through and add alternative coords for each of the locations in the db which stray from the map, which is a lot of work — and at this point, it's been so long since I put together this list (by hand) that I can't remember just how many are out of sync (and I don't have the same kind of time for WoW now as  I did then).

If you are happy to solve this, somehow, then I would be happy to merge, but I know it's a big ask.

Thanks!

**Comment by fubaWoW** [comment]
It just looks "wrong" because the Map-Texture IS "wrong"!
Means the Map-Texture is NOT aligned with the "Real" position.

Easy to test:
Go toMechanar, stand Outside of the Instance (dont enter) and Look on the Map where you are :D
And... Here we go:
image

And in addition to that it is because the "Zone-Map" (Netherstorm in this case) is still handled by Blizzard and not by InstancePortals!
That's why i also added the "extra function" in the comment above for the Waypoint Feature to work also on Zone-Maps because ALL your "Zone-Map Pins" are not Visible for me!

here is the Outlands Map with MY coords:
image
and here my Netherstorm Zone-Map with MY coords:
image

they are aligned with the Zone-Map Instance Portals from Blizzard

----

Here is the Outlands Map with YOUR coords:
image
and here the Netherstorm Zone-Map map with YOUR coords:
image

**Comment by steventroughtonsmith** [comment]
Looks like it's suffering from bit-rot, then — all of the map pins were aligned to the illustrations back when I put them all together in WoW 6.x. The map texture is illustrative, not 'wrong' — it's not to scale, for artistic reasons. Before adding waypoints as per this pull request, only the map texture matters, which is why I took that approach instead of placing them with precise coords. Portal icons floating in the middle of the sky around e.g. Tempest Keep isn't really useful to anybody.

Grouping them doesn't fix this at all, as there are four floating platforms at Tempest Keep and it helps to know which one is the right one to go to. When I built this, it was very much to avoid the 'go zone into each of the instance portals to see if it's the correct one' situation of the base game.

The maps have been re-drawn too, at a higher resolution, which has changed the location of things. There was a basic representation of Tempest Keep on the Outland map before it was re-drawn, which the four portals were aligned to.

If I were to update the addon, I would want to fix all of these discrepancies, and I'm not super enthusiastic to do that now that Blizzard is adding the map pins themselves (and getting them wrong, if that's the case). All these pins were hand placed for a reason

**Comment by fubaWoW** [comment]
Yeah anyway... what to say? Just -> Use it or not.
I've also added all the existing  Dragonflight Instances (7 for now) and Raids (actually just 1 for now)

> Before adding waypoints as per this pull request, only the map texture matters, which is why I took that approach instead of placing them with precise coords.

This is not correct 100% because if you stand "in front of the Instance" the InstancePortals Pins are not correct (because for the Map the Player "fly") :D
Also back then in Burning Crusade, the Player Position was "wrong" on especially this Map if you were in front of the Instance Entrance.
So this is a very old and known (lets say) bug and will never get fixed until "Netherstorm" will be Re-Designed (what will not happen anymore i think)

For short, there is **no chance** to "fix" this (except you re-design the map for sure) because it can be either ``accurate -> player position matches with pins in front of the Instance`` or just ``looks good but pins are at different positions as the entrance is``!

I will use it for a ``show me the REAL Entrance`` reason not for a ``looks good, but is wrong coordinates`` reason ^^
Just because i like to see where is the Entrance FOR REAL when i want to fly over to an Instance

**Comment by fubaWoW** [comment]
> If you're already standing at the instance portal, it doesn't really matter where the map pin is 😂 

**EXACTLY** -> **Everyone** want to know "***where exactly***" the Entrance is while NOT in front of the Instance!
That is the **ONLY** reason to show an Instance Portal Pin at all 👍
So the Instance Portal Map-Pin have to be "exactly in Front of the Instance", so EVERYONE can find the Entrance even if they do not know the Position!

I'm sure you dont like the Map-Pin of Zul'Farrak is shown in the Barrens or at Booty Bay, NO you want it "exactly" in Front of... guess where?... Zul'Farrak -> yey!!! 🥳 

> If you want to see where the entrance is visually based on the illustration

Yeah that is the problem, you can not find the entrance then because it is not there 🤣

**Comment by steventroughtonsmith** [comment]
No point in going round in circles on this one.

**Comment by fubaWoW** [comment]
there is no circle, just a "wall" it seems 🥲 
i've deleted my fork and maybe i'll do a fan update any time
have a nice day

**Comment by Lovasz-Akos** [comment]
hey I wanted to ask where you got the ids for taza and sepulcher, i'm adding dragonflight dungeons and I can't figure out what the ids stand for (this one -> [1193] <-- ={"Sepulcher of the First Ones", 2, 60, 9},)

**Comment by fubaWoW** [comment]
> hey I wanted to ask where you got the ids for taza and sepulcher, i'm adding dragonflight dungeons and I can't figure out what the ids stand for (this one -> [1193] <-- ={"Sepulcher of the First Ones", 2, 60, 9},)
this is the "journalInstanceID" to open the correct Journal Page by clicking the Instance-Icon at the Map.

It comes from a table of the ``C_EncounterJournal.GetDungeonEntrancesForMap(zone_mapID)`` function

i've actually no active subscription but i will try to update the new instances soon!

btw, i use my own function to get all the info i need:
```
function fuba_GetDataForInstancePortals()
	local done = {}
	local uiMapID = WorldMapFrame:GetMapID();
	if not uiMapID then return end
	local mapChildren = C_Map.GetMapChildrenInfo(uiMapID, Enum.UIMapType.Zone)
	if ( (type(mapChildren) ~= 'table') or (#mapChildren < 1) ) then return end

	local text = string.format("\n\n\[%d\]={", uiMapID) -- add MapID for current selected Map
	local text2 = "\n"
	--print(string.format("\n\n\[%d\]={", uiMapID)) -- add MapID for current selected Map

	for _, childMapInfo in ipairs(mapChildren) do
		if childMapInfo then
			local zone_name = childMapInfo.name
			local zone_mapID = childMapInfo.mapID
			if (zone_name) then
				local dungeonEntrances = C_EncounterJournal.GetDungeonEntrancesForMap(zone_mapID);
				if ( (type(dungeonEntrances) == 'table') and (#dungeonEntrances > 0) ) then
					--print(string.format("\n  -- %s", zone_name)) -- add Zone Name, just for details and overview!
					text = text..string.format("\n  -- %s", zone_name)

					local dungeon_name, dungeon_position, dungeon_instanceID, dungeon_Type
					for _, dungeonEntranceInfo in ipairs(dungeonEntrances) do
						dungeon_name = dungeonEntranceInfo.name
						dungeon_atlasName = dungeonEntranceInfo.atlasName
						dungeon_position = dungeonEntranceInfo.position
						dungeon_instanceID = dungeonEntranceInfo.journalInstanceID
						if (done[dungeon_instanceID] ~= true) then
							if dungeon_name and dungeon_position and dungeon_instanceID then
								local pos_vector = CreateVector2D(dungeon_position.x, dungeon_position.y)
								if pos_vector then
									local continentID, worldPosition = C_Map.GetWorldPosFromMapPos(zone_mapID, pos_vector)
									if worldPosition then
										local _, mapPosition = C_Map.GetMapPosFromWorldPos(continentID, worldPosition)

										if mapPosition then
											--local formatedtext = string.format("  {%f, %f, {%d}}, -- %s", (mapPosition.x*100), (mapPosition.y*100), dungeon_instanceID, dungeon_name)
											--print(formatedtext)
											text = text.."\n"..string.format("  {%f, %f, {%d}}, -- %s", (mapPosition.x*100), (mapPosition.y*100), dungeon_instanceID, dungeon_name)
											dungeon_Type = (dungeon_atlasName and dungeon_atlasName == "Raid") and 2 or 1
											text2 = text2.."\n"..string.format("["..dungeon_instanceID.."]={\""..dungeon_name.."\", "..dungeon_Type..", 1, 10},")

											done[dungeon_instanceID] = true;
										end

									end
								end
							end
						end
					end
				end
			end
		end
	end
	text = text.."\n}"
	print(text)
	print(text2)
end
```
inGame usage: ``/run fuba_GetDataForInstancePortals()``

while a Sub-Continent Map (like Dragon Isles, Kalimdor, Draenor or Northrend) is open

it also may work at the Main World Map but can cause a game crash, so Sub-Continent Maps are recommended 🤣

**Comment by Lovasz-Akos** [comment]
lovely, thank you, weirdly the icons still don't show up even though I don't think I really missed anything in #18

**Comment by fubaWoW** [comment]
> lovely, thank you, weirdly the icons still don't show up even though I don't think I really missed anything in #18
YW but...
Why not use my fork "[Instance Portals Advanced](https://www.curseforge.com/wow/addons/instance-portals-advanced)" what already contains all instances for Shadowlands and DF since Dec 2022 and also some other features? 😉

**Pull request closed without merging**
